### ISSUE TITLE
Some PHIR gates not supported by Stabilizer simulator 

### ISSUE THREAD

**Issue by IlanIwumbwe** [PECOS-packages/PECOS#69]
Related to [this](https://github.com/PECOS-packages/PECOS/issues/32).

Myself and [Benny](https://github.com/Bennybenassius) managed find a set of gates that aren't supported by the PHIR spec by running randomly generated Pytket circuits through the [pytket-pecos](https://github.com/CQCL/pytket-pecos) package. 

The circuits used to run on this backend are prepared such that all gates are defined in PHIR. We used [this dictionary](https://github.com/CQCL/pytket-phir/blob/main/pytket/phir/phirgen.py#L62-L93) to guide us.

Running:

``` Python
main_circ = Circuit(2, 2, "main_circ")
# Adding qregs and qubit resources 
qreg_0 = main_circ.add_q_register("qreg_0",1)
qreg_1 = main_circ.add_q_register("qreg_1",1)

# Applying gates 
main_circ.add_gate(OpType.YYPhase,[0.22],[qreg_0[0], qreg_1[0]])
main_circ.add_gate(OpType.SXdg,[qreg_1[0]])

main_circ.measure_all()
```

Leads to:
``` Python
KeyError                                  Traceback (most recent call last)
Cell In[283], line 2
      1 emu = Emulator(main_circ)
----> 2 print(emu.run(1))

File ~/Desktop/tket/lib/python3.11/site-packages/pytket_pecos/emulator.py:40, in Emulator.run(self, n_shots, multithreading)
     38 def run(self, n_shots, multithreading=False) -> OutcomeArray:
     39     runner = self.engine.run_multisim if multithreading else self.engine.run
---> 40     results = runner(self.phir, foreign_object=self.foreign_object, shots=n_shots)
     41     c_regs = sorted(results.keys())
     42     readouts = []

File ~/Desktop/tket/lib/python3.11/site-packages/pecos/engines/hybrid_engine.py:185, in HybridEngine.run(self, program, foreign_object, shots, seed, initialize, return_int)
    183 measurements.clear()
    184 for noisy_qops in self._internal_cinterp.execute(noisy_buffered_ops):
--> 185     temp_meas = self.qsim.run(noisy_qops)
    186     self._internal_cinterp.receive_results(temp_meas)
    187     measurements.extend(temp_meas)

File ~/Desktop/tket/lib/python3.11/site-packages/pecos/simulators/quantum_simulator.py:64, in QuantumSimulator.run(self, qops)
     62     op.metadata = {}
     63 if isinstance(op, QOp):
---> 64     output = self.state.run_gate(op.sim_name, op.args, **op.metadata)
     65     if op.returns:
...
---> 40 results = self.bindings[symbol](self, location, **params)
     42 # TODO: get params var value ... -> result = {'sym':, 'index':, 'result': result, 'qubit': location}
     44 if results:

KeyError: 'RYY'
```

The same happens for these Pytket gates: `YYPhase`, `Rx`, `Ry`, `Rz`, `XXPhase`, `ZZPhase`, `Tdg`, `T`, `TK2`, `PhasedX`, `U1`

Looking through the source code, we found that the PHIR equivalents of theese gates aren't implemented [here](https://github.com/PECOS-packages/PECOS/blob/master/pecos/simulators/_sparsesim/bindings.py).

This isn't stated explicitly anywhere, and would be nice to have implemeted.

**Comment by qciaran** [comment]
Hi, thanks for the bug report! What seems to be happening is gates are being requested for a simulator that cannot not support them even in theory. Stabilizer simulators can only apply Clifford and measurement-like gates.

So this only a bug on the PECOS side, if these gates that are being supplied are not equivalent to Cliffords. If they are, they there is a fault in the identification of general rotations to Cliffords.

However, either way, it does seem like maybe an improvement in documentation and/or error messaging might be called for.

**Comment by IlanIwumbwe** [comment]
Ah, I see. Thanks for your response!

**Comment by qciaran** [comment]
No worries. Looking more closely into pytket-pecos, it looks like the stabilizer simulator is default. You can change the default by using the argument `qsim`, so you may want to try `Emulator(..., qsim="state-vector")`. Here are the list of possible options:

`["stabilizer", "state-vector", "ProjectQSim", "MPS", "mps", "Qulacs", "QuEST", "CuStateVec"]`

Some of these require non-default requirements. Primarily installing cude/quQUantum. See Section "Simulators with special requirements" in  Readme: https://github.com/PECOS-packages/PECOS/tree/development

**Comment by IlanIwumbwe** [comment]
Thank you!
